In [1]:
import nfl_data_py as nfl
import pandas as pd
import numpy as np
import os
import sys
module_path = os.path.abspath(os.path.join('../../../../'))
if module_path not in sys.path:
    sys.path.append(module_path)
print(module_path)

c:\Users\jkcru\nfl-predictions

In [2]:
from src.data.next_gen_stats import collect as next_gen_collect
from src.data.play_by_play import collect as pbp_collect
from src.data.weekly import collect as weekly_collect
from src.data.schedule import collect as schedule_collect

In [3]:
weekly_df = weekly_collect.get_weekly_data(2022)
weekly_df.head()

Downcasting floats.

,team,season,week,season_type,opp_team,team_game_count,opp_game_count,off_completions,off_completions_cumulative_average,off_completions_cumulative_average_change,...,def_opp_receiving_fumbles_lost_cumulative_average_change,def_opp_racr,def_opp_racr_cumulative_average,def_opp_racr_cumulative_average_change,def_opp_wopr,def_opp_wopr_cumulative_average,def_opp_wopr_cumulative_average_change,def_opp_special_teams_tds,def_opp_special_teams_tds_cumulative_average,def_opp_special_teams_tds_cumulative_average_change
0,ARI,2022,1,REG,KC,1,1,24,24.000000,0.000000,...,-0.105263,23.363949,23.363949,15.856057,2.2,2.2,8.783842e-08,0.0,0.0,0.0
1,ARI,2022,2,REG,LV,2,2,31,27.500000,3.500000,...,0.000000,4.044793,0.979190,3.065603,2.2,2.2,0.000000e+00,0.0,0.0,0.0
2,ARI,2022,3,REG,LA,3,3,37,30.666667,3.166667,...,0.000000,-14.124653,-9.009686,-2.557483,2.2,2.2,7.947286e-08,0.0,0.0,0.0
3,ARI,2022,4,REG,CAR,4,4,23,28.750000,-1.916667,...,0.000000,1.130505,5.242867,-1.370787,2.2,2.2,-7.947286e-08,0.0,0.0,0.0
4,ARI,2022,5,REG,PHI,5,5,28,28.600000,-0.150000,...,0.000000,-14.683343,0.285951,-3.742323,2.2,2.2,-4.768372e-08,0.0,0.0,0.0

In [4]:
weekly_df.columns.to_list()

['team',
 'season',
 'week',
 'season_type',
 'opp_team',
 'team_game_count',
 'opp_game_count',
 'off_completions',
 'off_completions_cumulative_average',
 'off_completions_cumulative_average_change',
 'off_attempts',
 'off_attempts_cumulative_average',
 'off_attempts_cumulative_average_change',
 'off_passing_yards',
 'off_passing_yards_cumulative_average',
 'off_passing_yards_cumulative_average_change',
 'off_passing_tds',
 'off_passing_tds_cumulative_average',
 'off_passing_tds_cumulative_average_change',
 'off_interceptions',
 'off_interceptions_cumulative_average',
 'off_interceptions_cumulative_average_change',
 'off_sacks',
 'off_sacks_cumulative_average',
 'off_sacks_cumulative_average_change',
 'off_sack_yards',
 'off_sack_yards_cumulative_average',
 'off_sack_yards_cumulative_average_change',
 'off_sack_fumbles',
 'off_sack_fumbles_cumulative_average',
 'off_sack_fumbles_cumulative_average_change',
 'off_sack_fumbles_lost',
 'off_sack_fumbles_lost_cumulative_average',
 'off_sack_fumbles_lost_cumulative_average_change',
 'off_passing_air_yards',
 'off_passing_air_yards_cumulative_average',
 'off_passing_air_yards_cumulative_average_change',
 'off_passing_yards_after_catch',
 'off_passing_yards_after_catch_cumulative_average',
 'off_passing_yards_after_catch_cumulative_average_change',
 'off_passing_first_downs',
 'off_passing_first_downs_cumulative_average',
 'off_passing_first_downs_cumulative_average_change',
 'off_passing_epa',
 'off_passing_epa_cumulative_average',
 'off_passing_epa_cumulative_average_change',
 'off_pacr',
 'off_pacr_cumulative_average',
 'off_pacr_cumulative_average_change',
 'off_dakota',
 'off_dakota_cumulative_average',
 'off_dakota_cumulative_average_change',
 'off_carries',
 'off_carries_cumulative_average',
 'off_carries_cumulative_average_change',
 'off_rushing_yards',
 'off_rushing_yards_cumulative_average',
 'off_rushing_yards_cumulative_average_change',
 'off_rushing_tds',
 'off_rushing_tds_cumulative_average',
 'off_rushing_tds_cumulative_average_change',
 'off_rushing_fumbles',
 'off_rushing_fumbles_cumulative_average',
 'off_rushing_fumbles_cumulative_average_change',
 'off_rushing_fumbles_lost',
 'off_rushing_fumbles_lost_cumulative_average',
 'off_rushing_fumbles_lost_cumulative_average_change',
 'off_rushing_first_downs',
 'off_rushing_first_downs_cumulative_average',
 'off_rushing_first_downs_cumulative_average_change',
 'off_rushing_epa',
 'off_rushing_epa_cumulative_average',
 'off_rushing_epa_cumulative_average_change',
 'off_receiving_fumbles',
 'off_receiving_fumbles_cumulative_average',
 'off_receiving_fumbles_cumulative_average_change',
 'off_receiving_fumbles_lost',
 'off_receiving_fumbles_lost_cumulative_average',
 'off_receiving_fumbles_lost_cumulative_average_change',
 'off_racr',
 'off_racr_cumulative_average',
 'off_racr_cumulative_average_change',
 'off_wopr',
 'off_wopr_cumulative_average',
 'off_wopr_cumulative_average_change',
 'off_special_teams_tds',
 'off_special_teams_tds_cumulative_average',
 'off_special_teams_tds_cumulative_average_change',
 'def_opp_completions',
 'def_opp_completions_cumulative_average',
 'def_opp_completions_cumulative_average_change',
 'def_opp_attempts',
 'def_opp_attempts_cumulative_average',
 'def_opp_attempts_cumulative_average_change',
 'def_opp_passing_yards',
 'def_opp_passing_yards_cumulative_average',
 'def_opp_passing_yards_cumulative_average_change',
 'def_opp_passing_tds',
 'def_opp_passing_tds_cumulative_average',
 'def_opp_passing_tds_cumulative_average_change',
 'def_opp_interceptions',
 'def_opp_interceptions_cumulative_average',
 'def_opp_interceptions_cumulative_average_change',
 'def_opp_sacks',
 'def_opp_sacks_cumulative_average',
 'def_opp_sacks_cumulative_average_change',
 'def_opp_sack_yards',
 'def_opp_sack_yards_cumulative_average',
 'def_opp_sack_yards_cumulative_average_change',
 'def_opp_sack_fumbles',
 'def_opp_sack_fumbles_cumulative_average',
 'def_opp_sack_fumbles_cumulative_average_change',
 'def_opp_sack_fumbles_lost',
 'def_opp_sack_fumbles_lost_cumulative_average',
 'def_opp_sack_fumbles_lost_cumulative_average_change',
 'def_opp_passing_air_yards',
 'def_opp_passing_air_yards_cumulative_average',
 'def_opp_passing_air_yards_cumulative_average_change',
 'def_opp_passing_yards_after_catch',
 'def_opp_passing_yards_after_catch_cumulative_average',
 'def_opp_passing_yards_after_catch_cumulative_average_change',
 'def_opp_passing_first_downs',
 'def_opp_passing_first_downs_cumulative_average',
 'def_opp_passing_first_downs_cumulative_average_change',
 'def_opp_passing_epa',
 'def_opp_passing_epa_cumulative_average',
 'def_opp_passing_epa_cumulative_average_change',
 'def_opp_pacr',
 'def_opp_pacr_cumulative_average',
 'def_opp_pacr_cumulative_average_change',
 'def_opp_dakota',
 'def_opp_dakota_cumulative_average',
 'def_opp_dakota_cumulative_average_change',
 'def_opp_carries',
 'def_opp_carries_cumulative_average',
 'def_opp_carries_cumulative_average_change',
 'def_opp_rushing_yards',
 'def_opp_rushing_yards_cumulative_average',
 'def_opp_rushing_yards_cumulative_average_change',
 'def_opp_rushing_tds',
 'def_opp_rushing_tds_cumulative_average',
 'def_opp_rushing_tds_cumulative_average_change',
 'def_opp_rushing_fumbles',
 'def_opp_rushing_fumbles_cumulative_average',
 'def_opp_rushing_fumbles_cumulative_average_change',
 'def_opp_rushing_fumbles_lost',
 'def_opp_rushing_fumbles_lost_cumulative_average',
 'def_opp_rushing_fumbles_lost_cumulative_average_change',
 'def_opp_rushing_first_downs',
 'def_opp_rushing_first_downs_cumulative_average',
 'def_opp_rushing_first_downs_cumulative_average_change',
 'def_opp_rushing_epa',
 'def_opp_rushing_epa_cumulative_average',
 'def_opp_rushing_epa_cumulative_average_change',
 'def_opp_receiving_fumbles',
 'def_opp_receiving_fumbles_cumulative_average',
 'def_opp_receiving_fumbles_cumulative_average_change',
 'def_opp_receiving_fumbles_lost',
 'def_opp_receiving_fumbles_lost_cumulative_average',
 'def_opp_receiving_fumbles_lost_cumulative_average_change',
 'def_opp_racr',
 'def_opp_racr_cumulative_average',
 'def_opp_racr_cumulative_average_change',
 'def_opp_wopr',
 'def_opp_wopr_cumulative_average',
 'def_opp_wopr_cumulative_average_change',
 'def_opp_special_teams_tds',
 'def_opp_special_teams_tds_cumulative_average',
 'def_opp_special_teams_tds_cumulative_average_change']

In [5]:
weekly_df[weekly_df['team'] == 'CAR']

,team,season,week,season_type,opp_team,team_game_count,opp_game_count,off_completions,off_completions_cumulative_average,off_completions_cumulative_average_change,...,def_opp_receiving_fumbles_lost_cumulative_average_change,def_opp_racr,def_opp_racr_cumulative_average,def_opp_racr_cumulative_average_change,def_opp_wopr,def_opp_wopr_cumulative_average,def_opp_wopr_cumulative_average_change,def_opp_special_teams_tds,def_opp_special_teams_tds_cumulative_average,def_opp_special_teams_tds_cumulative_average_change
70,CAR,2022,1,REG,CLE,1,1,16,16.000000,-6.722222,...,-0.157895,2.295760,2.295760,-0.023479,2.2,2.2,8.783842e-08,0.0,0.0,0.0
71,CAR,2022,2,REG,NYG,2,2,14,15.000000,-1.000000,...,0.500000,-19.824198,-3.508168,-16.316030,2.2,2.2,0.000000e+00,0.0,0.0,0.0
72,CAR,2022,3,REG,NO,3,3,12,14.000000,-1.000000,...,-0.166667,109.280281,38.883362,35.198461,2.2,2.2,7.947286e-08,0.0,0.0,0.0
73,CAR,2022,4,REG,ARI,4,4,22,16.000000,2.000000,...,-0.166667,7.022721,1.886774,1.711982,2.2,2.2,-7.947286e-08,0.0,0.0,0.0
74,CAR,2022,5,REG,SF,5,5,25,17.800000,1.800000,...,0.000000,10.341655,2.804881,1.884193,2.2,2.2,-4.768372e-08,0.0,0.0,0.0
75,CAR,2022,6,REG,LA,6,6,13,17.000000,-0.800000,...,0.000000,-5.695833,0.137749,-1.166716,2.2,2.2,-3.178914e-08,0.0,0.0,0.0
76,CAR,2022,7,REG,TB,7,7,16,16.857143,-0.142857,...,-0.047619,12.284091,9.577479,0.451102,2.2,2.2,-4.541306e-08,0.0,0.0,0.0
77,CAR,2022,8,REG,ATL,8,8,19,17.125000,0.267857,...,-0.053571,7.519183,5.472310,0.292411,2.2,2.2,-3.405980e-08,0.0,0.0,0.0
78,CAR,2022,9,REG,CIN,9,9,17,17.111111,-0.013889,...,-0.013889,-37.014702,-0.746768,-4.533492,2.2,2.2,-1.324548e-07,0.0,0.0,0.0
79,CAR,2022,10,REG,ATL,10,10,10,16.400000,-0.711111,...,-0.033333,3.564215,4.825856,-0.140182,2.2,2.2,-1.271566e-07,0.0,0.0,0.0
80,CAR,2022,11,REG,BAL,11,10,21,16.818182,0.418182,...,0.066667,8.935101,1.040780,0.877147,2.2,2.2,8.477105e-08,0.0,0.0,0.0
81,CAR,2022,12,REG,DEN,12,11,11,16.333333,-0.484848,...,-0.018182,-1.606805,6.421644,-0.802845,2.2,2.2,6.935813e-08,0.0,0.0,0.0
82,CAR,2022,14,REG,SEA,13,13,14,16.153846,-0.179487,...,-0.012821,9.212454,6.972919,0.186627,2.2,2.2,6.113297e-08,0.0,0.0,0.0
83,CAR,2022,15,REG,PIT,14,14,14,16.000000,-0.153846,...,-0.005495,61.154354,9.341419,3.985610,2.2,2.2,5.239969e-08,0.0,0.0,0.0
84,CAR,2022,16,REG,DET,15,15,15,15.933333,-0.066667,...,-0.019048,7.233749,7.160660,0.005221,2.2,2.2,-8.174351e-08,0.0,0.0,0.0
85,CAR,2022,17,REG,TB,16,16,23,16.375000,0.441667,...,-0.008333,68.160629,10.084047,3.871773,2.2,2.2,4.768372e-08,0.0,0.0,0.0
86,CAR,2022,18,REG,NO,17,17,5,15.705882,-0.669118,...,-0.014706,1.235470,13.600326,-0.772803,2.2,2.2,4.207387e-08,0.0,0.0,0.0

In [6]:
schedule_df = schedule_collect.get_schedule_data(2022)
schedule_df

,game_id,season,game_type,week,away_team,away_score,home_team,home_score,div_game,home_days_since_previous_game,...,away_off_cumulative_avg_score,away_off_cumulative_avg_score_change,home_def_cumulative_points_allowed,home_def_cumulative_avg_points_allowed,home_def_cumulative_avg_points_allowed_change,away_def_cumulative_points_allowed,away_def_cumulative_avg_points_allowed,away_def_cumulative_avg_points_allowed_change,indoor,h_win
0,2022_01_BUF_LA,2022,REG,1,BUF,31,LA,10,0,240.0,...,31.000000,0.000000,31,31.000000,0.000000,10,10.000000,0.000000,1,0
1,2022_01_NO_ATL,2022,REG,1,NO,27,ATL,26,1,240.0,...,27.000000,0.000000,27,27.000000,0.000000,26,26.000000,0.000000,1,0
2,2022_01_CLE_CAR,2022,REG,1,CLE,26,CAR,24,0,240.0,...,26.000000,0.000000,26,26.000000,0.000000,24,24.000000,0.000000,1,0
3,2022_01_SF_CHI,2022,REG,1,SF,10,CHI,19,0,240.0,...,10.000000,0.000000,10,10.000000,0.000000,19,19.000000,0.000000,1,1
4,2022_01_PIT_CIN,2022,REG,1,PIT,23,CIN,20,1,240.0,...,23.000000,0.000000,23,23.000000,0.000000,20,20.000000,0.000000,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,2022_20_CIN_BUF,2022,DIV,20,CIN,27,BUF,10,0,7.0,...,26.055556,0.055556,344,19.111111,0.464052,349,19.388889,-0.552288,1,0
280,2022_20_DAL_SF,2022,DIV,20,DAL,12,SF,19,0,8.0,...,26.842105,-0.824561,312,16.421053,-0.245614,375,19.736842,-0.040936,1,1
281,2022_21_SF_PHI,2022,CON,21,SF,7,PHI,31,0,8.0,...,25.850000,-0.992105,358,18.842105,-0.657895,343,17.150000,0.728947,1,1
282,2022_21_CIN_KC,2022,CON,21,CIN,20,KC,23,0,8.0,...,25.736842,-0.318713,409,21.526316,-0.084795,372,19.578947,0.190058,1,1
283,2022_22_KC_PHI,2022,SB,22,KC,38,PHI,35,0,14.0,...,29.200000,0.463158,396,19.800000,0.957895,444,22.200000,0.673684,1,0

In [7]:
schedule_df.columns.to_list()

['game_id',
 'season',
 'game_type',
 'week',
 'away_team',
 'away_score',
 'home_team',
 'home_score',
 'div_game',
 'home_days_since_previous_game',
 'home_off_cumulative_score',
 'home_off_cumulative_avg_score',
 'home_off_cumulative_avg_score_change',
 'away_days_since_previous_game',
 'away_off_cumulative_score',
 'away_off_cumulative_avg_score',
 'away_off_cumulative_avg_score_change',
 'home_def_cumulative_points_allowed',
 'home_def_cumulative_avg_points_allowed',
 'home_def_cumulative_avg_points_allowed_change',
 'away_def_cumulative_points_allowed',
 'away_def_cumulative_avg_points_allowed',
 'away_def_cumulative_avg_points_allowed_change',
 'indoor',
 'h_win']

In [8]:
schedule_df[schedule_df['week'] == 14][['game_id', 'season', 'game_type', 'week',
                                       'away_team', 'away_score', 'home_team', 'home_score',
                                       'home_days_since_previous_game', 'away_days_since_previous_game']]
                                    #    'home_days_to_bye_week', 'away_days_to_bye_week']]

,game_id,season,game_type,week,away_team,away_score,home_team,home_score,home_days_since_previous_game,away_days_since_previous_game
195,2022_14_LV_LA,2022,REG,14,LV,16,LA,17,4.0,4.0
196,2022_14_NYJ_BUF,2022,REG,14,NYJ,12,BUF,20,10.0,7.0
197,2022_14_CLE_CIN,2022,REG,14,CLE,10,CIN,23,7.0,7.0
198,2022_14_HOU_DAL,2022,REG,14,HOU,23,DAL,27,7.0,7.0
199,2022_14_MIN_DET,2022,REG,14,MIN,23,DET,34,7.0,7.0
200,2022_14_PHI_NYG,2022,REG,14,PHI,48,NYG,22,7.0,7.0
201,2022_14_BAL_PIT,2022,REG,14,BAL,16,PIT,14,7.0,7.0
202,2022_14_JAX_TEN,2022,REG,14,JAX,36,TEN,22,7.0,7.0
203,2022_14_KC_DEN,2022,REG,14,KC,34,DEN,28,7.0,7.0
204,2022_14_CAR_SEA,2022,REG,14,CAR,30,SEA,24,7.0,14.0
205,2022_14_TB_SF,2022,REG,14,TB,7,SF,35,7.0,6.0
206,2022_14_MIA_LAC,2022,REG,14,MIA,17,LAC,23,7.0,7.0
207,2022_14_NE_ARI,2022,REG,14,NE,27,ARI,13,15.0,11.0

The home_days_to_bye_week and away_days_to_bye_week are still not correct.

In [9]:
schedule_df[schedule_df['week'] == 13][['game_id', 'season', 'game_type', 'week',
                                       'away_team', 'away_score', 'home_team', 'home_score',
                                       'home_days_since_previous_game', 'away_days_since_previous_game']]
                                    #    'home_days_to_bye_week', 'away_days_to_bye_week']]

,game_id,season,game_type,week,away_team,away_score,home_team,home_score,home_days_since_previous_game,away_days_since_previous_game
180,2022_13_BUF_NE,2022,REG,13,BUF,24,NE,10,7.0,7.0
181,2022_13_PIT_ATL,2022,REG,13,PIT,19,ATL,16,7.0,6.0
182,2022_13_DEN_BAL,2022,REG,13,DEN,9,BAL,10,7.0,7.0
183,2022_13_GB_CHI,2022,REG,13,GB,28,CHI,19,7.0,7.0
184,2022_13_JAX_DET,2022,REG,13,JAX,14,DET,40,10.0,7.0
185,2022_13_CLE_HOU,2022,REG,13,CLE,27,HOU,14,7.0,7.0
186,2022_13_NYJ_MIN,2022,REG,13,NYJ,22,MIN,27,10.0,7.0
187,2022_13_WAS_NYG,2022,REG,13,WAS,20,NYG,20,10.0,7.0
188,2022_13_TEN_PHI,2022,REG,13,TEN,10,PHI,35,7.0,7.0
189,2022_13_SEA_LA,2022,REG,13,SEA,27,LA,23,7.0,7.0
190,2022_13_MIA_SF,2022,REG,13,MIA,17,SF,33,7.0,7.0
191,2022_13_KC_CIN,2022,REG,13,KC,24,CIN,27,7.0,7.0
192,2022_13_LAC_LV,2022,REG,13,LAC,20,LV,27,7.0,7.0
193,2022_13_IND_DAL,2022,REG,13,IND,19,DAL,54,10.0,6.0
194,2022_13_NO_TB,2022,REG,13,NO,16,TB,17,8.0,8.0

The weekly data does not have target_days_since_previous_game, but the schedule and weekly data does. I can identify the bye with target_days_since_previous_game between 10 and 20, but Josh may want it added in /nfl-predictions/src/data/weekly/collect.py. \

I have made the changes in /nfl-predictions/src/data/schedule/collect.py

If I add it to /nfl-predictions/src/data/weekly/collect.py, I can find the bye using the week column and look for the missing week number for each team each year. Ex: Panthers had a bye in week 13 above.

Once the bye is identified, add a column for days_to_bye_week that is positive when the bye has not occurred and negative after it occurs.

In [10]:
from src.data.collect_all import get_schedule_and_weekly_data
schedule_and_weekly_df = get_schedule_and_weekly_data([2019, 2021, 2022])
schedule_and_weekly_df.head()

Downcasting floats.
Downcasting floats.
Downcasting floats.

,game_id,season,game_type,week,opp_team,opp_score,target_team,target_score,div_game,target_days_since_previous_game,...,def_target_racr_cumulative_average,def_target_racr_cumulative_average_change,def_target_wopr,def_target_wopr_cumulative_average,def_target_wopr_cumulative_average_change,def_target_special_teams_tds,def_target_special_teams_tds_cumulative_average,def_target_special_teams_tds_cumulative_average_change,is_home_target,target_win
0,2019_01_GB_CHI,2019,REG,1,GB,10,CHI,3,1,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,2019_01_LA_CAR,2019,REG,1,LA,30,CAR,27,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
2,2019_01_TEN_CLE,2019,REG,1,TEN,43,CLE,13,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
3,2019_01_KC_JAX,2019,REG,1,KC,40,JAX,26,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,2019_01_BAL_MIA,2019,REG,1,BAL,59,MIA,10,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [11]:
schedule_and_weekly_df.columns.to_list()

['game_id',
 'season',
 'game_type',
 'week',
 'opp_team',
 'opp_score',
 'target_team',
 'target_score',
 'div_game',
 'target_days_since_previous_game',
 'target_off_cumulative_score',
 'target_off_cumulative_avg_score',
 'target_off_cumulative_avg_score_change',
 'opp_days_since_previous_game',
 'opp_off_cumulative_score',
 'opp_off_cumulative_avg_score',
 'opp_off_cumulative_avg_score_change',
 'target_def_cumulative_points_allowed',
 'target_def_cumulative_avg_points_allowed',
 'target_def_cumulative_avg_points_allowed_change',
 'opp_def_cumulative_points_allowed',
 'opp_def_cumulative_avg_points_allowed',
 'opp_def_cumulative_avg_points_allowed_change',
 'indoor',
 'h_win',
 'season_type',
 'target_game_count',
 'opp_game_count',
 'off_target_completions',
 'off_target_completions_cumulative_average',
 'off_target_completions_cumulative_average_change',
 'off_target_attempts',
 'off_target_attempts_cumulative_average',
 'off_target_attempts_cumulative_average_change',
 'off_target_passing_yards',
 'off_target_passing_yards_cumulative_average',
 'off_target_passing_yards_cumulative_average_change',
 'off_target_passing_tds',
 'off_target_passing_tds_cumulative_average',
 'off_target_passing_tds_cumulative_average_change',
 'off_target_interceptions',
 'off_target_interceptions_cumulative_average',
 'off_target_interceptions_cumulative_average_change',
 'off_target_sacks',
 'off_target_sacks_cumulative_average',
 'off_target_sacks_cumulative_average_change',
 'off_target_sack_yards',
 'off_target_sack_yards_cumulative_average',
 'off_target_sack_yards_cumulative_average_change',
 'off_target_sack_fumbles',
 'off_target_sack_fumbles_cumulative_average',
 'off_target_sack_fumbles_cumulative_average_change',
 'off_target_sack_fumbles_lost',
 'off_target_sack_fumbles_lost_cumulative_average',
 'off_target_sack_fumbles_lost_cumulative_average_change',
 'off_target_passing_air_yards',
 'off_target_passing_air_yards_cumulative_average',
 'off_target_passing_air_yards_cumulative_average_change',
 'off_target_passing_yards_after_catch',
 'off_target_passing_yards_after_catch_cumulative_average',
 'off_target_passing_yards_after_catch_cumulative_average_change',
 'off_target_passing_first_downs',
 'off_target_passing_first_downs_cumulative_average',
 'off_target_passing_first_downs_cumulative_average_change',
 'off_target_passing_epa',
 'off_target_passing_epa_cumulative_average',
 'off_target_passing_epa_cumulative_average_change',
 'off_target_pacr',
 'off_target_pacr_cumulative_average',
 'off_target_pacr_cumulative_average_change',
 'off_target_dakota',
 'off_target_dakota_cumulative_average',
 'off_target_dakota_cumulative_average_change',
 'off_target_carries',
 'off_target_carries_cumulative_average',
 'off_target_carries_cumulative_average_change',
 'off_target_rushing_yards',
 'off_target_rushing_yards_cumulative_average',
 'off_target_rushing_yards_cumulative_average_change',
 'off_target_rushing_tds',
 'off_target_rushing_tds_cumulative_average',
 'off_target_rushing_tds_cumulative_average_change',
 'off_target_rushing_fumbles',
 'off_target_rushing_fumbles_cumulative_average',
 'off_target_rushing_fumbles_cumulative_average_change',
 'off_target_rushing_fumbles_lost',
 'off_target_rushing_fumbles_lost_cumulative_average',
 'off_target_rushing_fumbles_lost_cumulative_average_change',
 'off_target_rushing_first_downs',
 'off_target_rushing_first_downs_cumulative_average',
 'off_target_rushing_first_downs_cumulative_average_change',
 'off_target_rushing_epa',
 'off_target_rushing_epa_cumulative_average',
 'off_target_rushing_epa_cumulative_average_change',
 'off_target_receiving_fumbles',
 'off_target_receiving_fumbles_cumulative_average',
 'off_target_receiving_fumbles_cumulative_average_change',
 'off_target_receiving_fumbles_lost',
 'off_target_receiving_fumbles_lost_cumulative_average',
 'off_target_receiving_fumbles_lost_cumulative_average_change',
 'off_target_racr',
 'off_target_racr_cumulative_average',
 'off_target_racr_cumulative_average_change',
 'off_target_wopr',
 'off_target_wopr_cumulative_average',
 'off_target_wopr_cumulative_average_change',
 'off_target_special_teams_tds',
 'off_target_special_teams_tds_cumulative_average',
 'off_target_special_teams_tds_cumulative_average_change',
 'def_opp_completions',
 'def_opp_completions_cumulative_average',
 'def_opp_completions_cumulative_average_change',
 'def_opp_attempts',
 'def_opp_attempts_cumulative_average',
 'def_opp_attempts_cumulative_average_change',
 'def_opp_passing_yards',
 'def_opp_passing_yards_cumulative_average',
 'def_opp_passing_yards_cumulative_average_change',
 'def_opp_passing_tds',
 'def_opp_passing_tds_cumulative_average',
 'def_opp_passing_tds_cumulative_average_change',
 'def_opp_interceptions',
 'def_opp_interceptions_cumulative_average',
 'def_opp_interceptions_cumulative_average_change',
 'def_opp_sacks',
 'def_opp_sacks_cumulative_average',
 'def_opp_sacks_cumulative_average_change',
 'def_opp_sack_yards',
 'def_opp_sack_yards_cumulative_average',
 'def_opp_sack_yards_cumulative_average_change',
 'def_opp_sack_fumbles',
 'def_opp_sack_fumbles_cumulative_average',
 'def_opp_sack_fumbles_cumulative_average_change',
 'def_opp_sack_fumbles_lost',
 'def_opp_sack_fumbles_lost_cumulative_average',
 'def_opp_sack_fumbles_lost_cumulative_average_change',
 'def_opp_passing_air_yards',
 'def_opp_passing_air_yards_cumulative_average',
 'def_opp_passing_air_yards_cumulative_average_change',
 'def_opp_passing_yards_after_catch',
 'def_opp_passing_yards_after_catch_cumulative_average',
 'def_opp_passing_yards_after_catch_cumulative_average_change',
 'def_opp_passing_first_downs',
 'def_opp_passing_first_downs_cumulative_average',
 'def_opp_passing_first_downs_cumulative_average_change',
 'def_opp_passing_epa',
 'def_opp_passing_epa_cumulative_average',
 'def_opp_passing_epa_cumulative_average_change',
 'def_opp_pacr',
 'def_opp_pacr_cumulative_average',
 'def_opp_pacr_cumulative_average_change',
 'def_opp_dakota',
 'def_opp_dakota_cumulative_average',
 'def_opp_dakota_cumulative_average_change',
 'def_opp_carries',
 'def_opp_carries_cumulative_average',
 'def_opp_carries_cumulative_average_change',
 'def_opp_rushing_yards',
 'def_opp_rushing_yards_cumulative_average',
 'def_opp_rushing_yards_cumulative_average_change',
 'def_opp_rushing_tds',
 'def_opp_rushing_tds_cumulative_average',
 'def_opp_rushing_tds_cumulative_average_change',
 'def_opp_rushing_fumbles',
 'def_opp_rushing_fumbles_cumulative_average',
 'def_opp_rushing_fumbles_cumulative_average_change',
 'def_opp_rushing_fumbles_lost',
 'def_opp_rushing_fumbles_lost_cumulative_average',
 'def_opp_rushing_fumbles_lost_cumulative_average_change',
 'def_opp_rushing_first_downs',
 'def_opp_rushing_first_downs_cumulative_average',
 'def_opp_rushing_first_downs_cumulative_average_change',
 'def_opp_rushing_epa',
 'def_opp_rushing_epa_cumulative_average',
 'def_opp_rushing_epa_cumulative_average_change',
 'def_opp_receiving_fumbles',
 'def_opp_receiving_fumbles_cumulative_average',
 'def_opp_receiving_fumbles_cumulative_average_change',
 'def_opp_receiving_fumbles_lost',
 'def_opp_receiving_fumbles_lost_cumulative_average',
 'def_opp_receiving_fumbles_lost_cumulative_average_change',
 'def_opp_racr',
 'def_opp_racr_cumulative_average',
 'def_opp_racr_cumulative_average_change',
 'def_opp_wopr',
 'def_opp_wopr_cumulative_average',
 'def_opp_wopr_cumulative_average_change',
 'def_opp_special_teams_tds',
 'def_opp_special_teams_tds_cumulative_average',
 'def_opp_special_teams_tds_cumulative_average_change',
 'off_opp_completions',
 'off_opp_completions_cumulative_average',
 'off_opp_completions_cumulative_average_change',
 'off_opp_attempts',
 'off_opp_attempts_cumulative_average',
 'off_opp_attempts_cumulative_average_change',
 'off_opp_passing_yards',
 'off_opp_passing_yards_cumulative_average',
 'off_opp_passing_yards_cumulative_average_change',
 'off_opp_passing_tds',
 'off_opp_passing_tds_cumulative_average',
 'off_opp_passing_tds_cumulative_average_change',
 'off_opp_interceptions',
 'off_opp_interceptions_cumulative_average',
 'off_opp_interceptions_cumulative_average_change',
 'off_opp_sacks',
 'off_opp_sacks_cumulative_average',
 'off_opp_sacks_cumulative_average_change',
 'off_opp_sack_yards',
 'off_opp_sack_yards_cumulative_average',
 'off_opp_sack_yards_cumulative_average_change',
 'off_opp_sack_fumbles',
 'off_opp_sack_fumbles_cumulative_average',
 'off_opp_sack_fumbles_cumulative_average_change',
 'off_opp_sack_fumbles_lost',
 'off_opp_sack_fumbles_lost_cumulative_average',
 'off_opp_sack_fumbles_lost_cumulative_average_change',
 'off_opp_passing_air_yards',
 'off_opp_passing_air_yards_cumulative_average',
 'off_opp_passing_air_yards_cumulative_average_change',
 'off_opp_passing_yards_after_catch',
 'off_opp_passing_yards_after_catch_cumulative_average',
 'off_opp_passing_yards_after_catch_cumulative_average_change',
 'off_opp_passing_first_downs',
 'off_opp_passing_first_downs_cumulative_average',
 'off_opp_passing_first_downs_cumulative_average_change',
 'off_opp_passing_epa',
 'off_opp_passing_epa_cumulative_average',
 'off_opp_passing_epa_cumulative_average_change',
 'off_opp_pacr',
 'off_opp_pacr_cumulative_average',
 'off_opp_pacr_cumulative_average_change',
 'off_opp_dakota',
 'off_opp_dakota_cumulative_average',
 'off_opp_dakota_cumulative_average_change',
 'off_opp_carries',
 'off_opp_carries_cumulative_average',
 'off_opp_carries_cumulative_average_change',
 'off_opp_rushing_yards',
 'off_opp_rushing_yards_cumulative_average',
 'off_opp_rushing_yards_cumulative_average_change',
 'off_opp_rushing_tds',
 'off_opp_rushing_tds_cumulative_average',
 'off_opp_rushing_tds_cumulative_average_change',
 'off_opp_rushing_fumbles',
 'off_opp_rushing_fumbles_cumulative_average',
 'off_opp_rushing_fumbles_cumulative_average_change',
 'off_opp_rushing_fumbles_lost',
 'off_opp_rushing_fumbles_lost_cumulative_average',
 'off_opp_rushing_fumbles_lost_cumulative_average_change',
 'off_opp_rushing_first_downs',
 'off_opp_rushing_first_downs_cumulative_average',
 'off_opp_rushing_first_downs_cumulative_average_change',
 'off_opp_rushing_epa',
 'off_opp_rushing_epa_cumulative_average',
 'off_opp_rushing_epa_cumulative_average_change',
 'off_opp_receiving_fumbles',
 'off_opp_receiving_fumbles_cumulative_average',
 'off_opp_receiving_fumbles_cumulative_average_change',
 'off_opp_receiving_fumbles_lost',
 'off_opp_receiving_fumbles_lost_cumulative_average',
 'off_opp_receiving_fumbles_lost_cumulative_average_change',
 'off_opp_racr',
 'off_opp_racr_cumulative_average',
 'off_opp_racr_cumulative_average_change',
 'off_opp_wopr',
 'off_opp_wopr_cumulative_average',
 'off_opp_wopr_cumulative_average_change',
 'off_opp_special_teams_tds',
 'off_opp_special_teams_tds_cumulative_average',
 'off_opp_special_teams_tds_cumulative_average_change',
 'def_target_completions',
 'def_target_completions_cumulative_average',
 'def_target_completions_cumulative_average_change',
 'def_target_attempts',
 'def_target_attempts_cumulative_average',
 'def_target_attempts_cumulative_average_change',
 'def_target_passing_yards',
 'def_target_passing_yards_cumulative_average',
 'def_target_passing_yards_cumulative_average_change',
 'def_target_passing_tds',
 'def_target_passing_tds_cumulative_average',
 'def_target_passing_tds_cumulative_average_change',
 'def_target_interceptions',
 'def_target_interceptions_cumulative_average',
 'def_target_interceptions_cumulative_average_change',
 'def_target_sacks',
 'def_target_sacks_cumulative_average',
 'def_target_sacks_cumulative_average_change',
 'def_target_sack_yards',
 'def_target_sack_yards_cumulative_average',
 'def_target_sack_yards_cumulative_average_change',
 'def_target_sack_fumbles',
 'def_target_sack_fumbles_cumulative_average',
 'def_target_sack_fumbles_cumulative_average_change',
 'def_target_sack_fumbles_lost',
 'def_target_sack_fumbles_lost_cumulative_average',
 'def_target_sack_fumbles_lost_cumulative_average_change',
 'def_target_passing_air_yards',
 'def_target_passing_air_yards_cumulative_average',
 'def_target_passing_air_yards_cumulative_average_change',
 'def_target_passing_yards_after_catch',
 'def_target_passing_yards_after_catch_cumulative_average',
 'def_target_passing_yards_after_catch_cumulative_average_change',
 'def_target_passing_first_downs',
 'def_target_passing_first_downs_cumulative_average',
 'def_target_passing_first_downs_cumulative_average_change',
 'def_target_passing_epa',
 'def_target_passing_epa_cumulative_average',
 'def_target_passing_epa_cumulative_average_change',
 'def_target_pacr',
 'def_target_pacr_cumulative_average',
 'def_target_pacr_cumulative_average_change',
 'def_target_dakota',
 'def_target_dakota_cumulative_average',
 'def_target_dakota_cumulative_average_change',
 'def_target_carries',
 'def_target_carries_cumulative_average',
 'def_target_carries_cumulative_average_change',
 'def_target_rushing_yards',
 'def_target_rushing_yards_cumulative_average',
 'def_target_rushing_yards_cumulative_average_change',
 'def_target_rushing_tds',
 'def_target_rushing_tds_cumulative_average',
 'def_target_rushing_tds_cumulative_average_change',
 'def_target_rushing_fumbles',
 'def_target_rushing_fumbles_cumulative_average',
 'def_target_rushing_fumbles_cumulative_average_change',
 'def_target_rushing_fumbles_lost',
 'def_target_rushing_fumbles_lost_cumulative_average',
 'def_target_rushing_fumbles_lost_cumulative_average_change',
 'def_target_rushing_first_downs',
 'def_target_rushing_first_downs_cumulative_average',
 'def_target_rushing_first_downs_cumulative_average_change',
 'def_target_rushing_epa',
 'def_target_rushing_epa_cumulative_average',
 'def_target_rushing_epa_cumulative_average_change',
 'def_target_receiving_fumbles',
 'def_target_receiving_fumbles_cumulative_average',
 'def_target_receiving_fumbles_cumulative_average_change',
 'def_target_receiving_fumbles_lost',
 'def_target_receiving_fumbles_lost_cumulative_average',
 'def_target_receiving_fumbles_lost_cumulative_average_change',
 'def_target_racr',
 'def_target_racr_cumulative_average',
 'def_target_racr_cumulative_average_change',
 'def_target_wopr',
 'def_target_wopr_cumulative_average',
 'def_target_wopr_cumulative_average_change',
 'def_target_special_teams_tds',
 'def_target_special_teams_tds_cumulative_average',
 'def_target_special_teams_tds_cumulative_average_change',
 'is_home_target',
 'target_win']

In [12]:
columns = [
    'game_id',
    'season',
    'game_type',
    'week',
    'opp_team',
    'opp_score',
    'target_team',
    'target_score',
    'div_game',
    'target_days_since_previous_game',
    # 'bye_week_target',
    # 'bye_week_opp',
    # 'target_days_to_bye_week',
    # 'opp_days_to_bye_week',
    'target_game_count',
    'opp_game_count',
    'is_home_target',
    'target_win'
]
schedule_and_weekly_df[schedule_and_weekly_df['target_team'] == 'CAR'][columns].sort_values('week')

,game_id,season,game_type,week,opp_team,opp_score,target_team,target_score,div_game,target_days_since_previous_game,target_game_count,opp_game_count,is_home_target,target_win
1,2019_01_LA_CAR,2019,REG,1,LA,30,CAR,27,0,240.0,1,1,1,0
554,2022_01_CLE_CAR,2022,REG,1,CLE,26,CAR,24,0,240.0,1,1,1,0
270,2021_01_NYJ_CAR,2021,REG,1,NYJ,14,CAR,19,0,240.0,1,1,1,1
284,2021_02_NO_CAR,2021,REG,2,NO,7,CAR,26,1,7.0,2,2,1,1
1410,2022_02_CAR_NYG,2022,REG,2,NYG,19,CAR,16,0,7.0,2,2,0,0
16,2019_02_TB_CAR,2019,REG,2,TB,20,CAR,14,1,4.0,2,2,1,0
877,2019_03_CAR_ARI,2019,REG,3,ARI,20,CAR,38,0,10.0,3,3,0,1
1135,2021_03_CAR_HOU,2021,REG,3,HOU,9,CAR,24,0,4.0,3,3,0,1
585,2022_03_NO_CAR,2022,REG,3,NO,14,CAR,22,1,7.0,3,3,1,1
1155,2021_04_CAR_DAL,2021,REG,4,DAL,36,CAR,28,0,10.0,4,4,0,0
889,2019_04_CAR_HOU,2019,REG,4,HOU,10,CAR,16,0,7.0,4,4,0,1
611,2022_04_ARI_CAR,2022,REG,4,ARI,26,CAR,16,0,7.0,4,4,1,0
627,2022_05_SF_CAR,2022,REG,5,SF,37,CAR,15,0,7.0,5,5,1,0
333,2021_05_PHI_CAR,2021,REG,5,PHI,21,CAR,18,0,7.0,5,5,1,0
64,2019_05_JAX_CAR,2019,REG,5,JAX,27,CAR,34,0,7.0,5,5,1,1
350,2021_06_MIN_CAR,2021,REG,6,MIN,34,CAR,28,0,7.0,6,6,1,0
1477,2022_06_CAR_LA,2022,REG,6,LA,24,CAR,10,0,7.0,6,6,0,0
915,2019_06_CAR_TB,2019,REG,6,TB,26,CAR,37,1,7.0,6,6,0,1
648,2022_07_TB_CAR,2022,REG,7,TB,3,CAR,21,1,7.0,7,7,1,1
1202,2021_07_CAR_NYG,2021,REG,7,NYG,25,CAR,3,0,7.0,7,7,0,0
1211,2021_08_CAR_ATL,2021,REG,8,ATL,13,CAR,19,1,7.0,8,7,0,1
1498,2022_08_CAR_ATL,2022,REG,8,ATL,37,CAR,34,1,7.0,8,8,0,0
952,2019_08_CAR_SF,2019,REG,8,SF,51,CAR,13,0,14.0,7,7,0,0
124,2019_09_TEN_CAR,2019,REG,9,TEN,20,CAR,30,0,7.0,8,9,1,1
391,2021_09_NE_CAR,2021,REG,9,NE,24,CAR,6,0,7.0,9,9,1,0
1514,2022_09_CAR_CIN,2022,REG,9,CIN,42,CAR,21,0,7.0,9,9,0,0
688,2022_10_ATL_CAR,2022,REG,10,ATL,15,CAR,25,1,4.0,10,10,1,1
1247,2021_10_CAR_ARI,2021,REG,10,ARI,10,CAR,34,0,7.0,10,10,0,1
980,2019_10_CAR_GB,2019,REG,10,GB,24,CAR,16,0,7.0,9,10,0,0
419,2021_11_WAS_CAR,2021,REG,11,WAS,27,CAR,21,0,7.0,11,10,1,0
1540,2022_11_CAR_BAL,2022,REG,11,BAL,13,CAR,3,0,10.0,11,10,0,0
150,2019_11_ATL_CAR,2019,REG,11,ATL,29,CAR,3,1,7.0,10,10,1,0
1004,2019_12_CAR_NO,2019,REG,12,NO,34,CAR,31,1,7.0,11,11,0,0
719,2022_12_DEN_CAR,2022,REG,12,DEN,10,CAR,23,0,7.0,12,11,1,1
1275,2021_12_CAR_MIA,2021,REG,12,MIA,33,CAR,10,0,7.0,12,12,0,0
180,2019_13_WAS_CAR,2019,REG,13,WAS,29,CAR,21,0,7.0,12,12,1,0
462,2021_14_ATL_CAR,2021,REG,14,ATL,29,CAR,21,1,14.0,13,13,1,0
1592,2022_14_CAR_SEA,2022,REG,14,SEA,24,CAR,30,0,14.0,13,13,0,1
1029,2019_14_CAR_ATL,2019,REG,14,ATL,40,CAR,20,1,7.0,13,13,0,0
209,2019_15_SEA_CAR,2019,REG,15,SEA,30,CAR,24,0,7.0,14,14,1,0
1313,2021_15_CAR_BUF,2021,REG,15,BUF,31,CAR,14,0,7.0,14,14,0,0
764,2022_15_PIT_CAR,2022,REG,15,PIT,24,CAR,16,0,7.0,14,14,1,0
778,2022_16_DET_CAR,2022,REG,16,DET,23,CAR,37,0,6.0,15,15,1,1
1065,2019_16_CAR_IND,2019,REG,16,IND,38,CAR,6,0,7.0,15,15,0,0
495,2021_16_TB_CAR,2021,REG,16,TB,32,CAR,6,1,7.0,15,15,1,0
1355,2021_17_CAR_NO,2021,REG,17,NO,18,CAR,10,1,7.0,16,16,0,0
1636,2022_17_CAR_TB,2022,REG,17,TB,30,CAR,24,1,8.0,16,16,0,0
241,2019_17_NO_CAR,2019,REG,17,NO,42,CAR,10,1,7.0,16,16,1,0
1373,2021_18_CAR_TB,2021,REG,18,TB,41,CAR,17,1,7.0,17,17,0,0
1651,2022_18_CAR_NO,2022,REG,18,NO,7,CAR,10,1,7.0,17,17,0,1

In [13]:
# Find the missing week for each team for each year
# Ensure you're only using regular season games
regular_season_df = schedule_and_weekly_df[schedule_and_weekly_df['game_type'] == 'REG']

# Get unique seasons and teams
seasons = regular_season_df['season'].unique()
teams = pd.unique(regular_season_df[['target_team', 'opp_team']].values.ravel())

bye_weeks = []

for season in seasons:
    season_df = regular_season_df[regular_season_df['season'] == season]
    weeks = season_df['week'].unique()

    for team in teams:
        for week in weeks:
            week_df = season_df[season_df['week'] == week]
            # Check if team plays this week (either as target or opp)
            plays_this_week = (
                (week_df['target_team'] == team) |
                (week_df['opp_team'] == team)
            ).any()

            if not plays_this_week:
                bye_weeks.append({
                    'team': team,
                    'season': season,
                    'bye_week': week
                })
                break  # Found the bye week, no need to check more weeks for this team

# Convert to DataFrame
bye_week_df = pd.DataFrame(bye_weeks)
bye_week_df

   team  season  bye_week
0   CHI    2019         6
1    GB    2019        11
2   CAR    2019         7
3    LA    2019         9
4   CLE    2019         7
..  ...     ...       ...
91  PIT    2022         9
92   NO    2022        14
93  HOU    2022         6
94   LV    2022         6
95  DEN    2022         9

[96 rows x 3 columns]

In [14]:
bye_week_df[bye_week_df['team'] == 'CAR']

   team  season  bye_week
2   CAR    2019         7
34  CAR    2021        13
66  CAR    2022        13